---

- name: install nginx
  hosts: all
  become: yes
  
  vars:
    src: /home/test-u/ansible
    dst: /etc/nginx/

  tasks:
    - block:

      - name: install nginx
        yum: name=nginx state=latest

      - name: copy template file conf
        template: src={{ src }}/nginx.j2 dest={{ dst }}/nginx.conf mode=0644

      - name: start webserver
        service: name=nginx state=started enabled=yes
      
      - name: reload nginx
        service: name=nginx state=reloaded


      when: ansible_os_family == "RedHat"
